import 'package:specspot/Model/Mobiles_model.dart';

final List<Phone> mobileunder20k = [
  Phone(
    name: 'Oppo A3 Pro',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'MediaTek Dimensity 810 5G',
    ram: '6 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.5 inches | IPS LCD',
    store: 'Amazon',
    price: '₹17,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'iQOO Z9',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Qualcomm Snapdragon 778G',
    ram: '8 GB RAM',
    camera: '64 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.67 inches | IPS LCD',
    store: 'Amazon',
    price: '₹21,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Realme 12 Pro',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'MediaTek Helio G96',
    ram: '8 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.43 inches | AMOLED',
    store: 'Flipkart',
    price: '₹16,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Realme 12 Plus',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'MediaTek Helio G96',
    ram: '6 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.43 inches | AMOLED',
    store: 'Flipkart',
    price: '₹14,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'OnePlus Nord 3 5G',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'MediaTek Dimensity 9000',
    ram: '8 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '4500 mAh',
    display: '6.74 inches | Fluid AMOLED',
    store: 'Amazon',
    price: '₹29,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Poco X6 5G',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Qualcomm Snapdragon 778G 5G',
    ram: '6 GB RAM',
    camera: '64 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.67 inches | IPS LCD',
    store: 'Flipkart',
    price: '₹19,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Samsung Galaxy F55 5G',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Exynos 1380',
    ram: '6 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.5 inches | Super AMOLED',
    store: 'Samsung Store',
    price: '₹22,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Realme Narzo 70 Pro',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'MediaTek Dimensity 920 5G',
    ram: '8 GB RAM',
    camera: '64 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.67 inches | Super AMOLED',
    store: 'Flipkart',
    price: '₹19,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'OnePlus Nord CE 3 5G',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Qualcomm Snapdragon 695 5G',
    ram: '8 GB RAM',
    camera: '64 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.72 inches | IPS LCD',
    store: 'Amazon',
    price: '₹19,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Poco X6 Pro',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Qualcomm Snapdragon 778G 5G',
    ram: '8 GB RAM',
    camera: '64 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.67 inches | IPS LCD',
    store: 'Flipkart',
    price: '₹21,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Vivo T3',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Qualcomm Snapdragon 778G',
    ram: '8 GB RAM',
    camera: '64 MP Rear Camera',
    battery: '4500 mAh',
    display: '6.44 inches | AMOLED',
    store: 'Amazon',
    price: '₹23,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Samsung Galaxy A35 5G',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Exynos 1380',
    ram: '6 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.5 inches | Super AMOLED',
    store: 'Samsung Store',
    price: '₹24,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Xiaomi Redmi Note 13 Pro',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'MediaTek Dimensity 920 5G',
    ram: '8 GB RAM',
    camera: '108 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.67 inches | AMOLED',
    store: 'Mi Store',
    price: '₹24,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'OnePlus Nord CE 4 Lite 5G',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Qualcomm Snapdragon 695 5G',
    ram: '6 GB RAM',
    camera: '64 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.59 inches | IPS LCD',
    store: 'Amazon',
    price: '₹18,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Xiaomi Redmi Note 13',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'MediaTek Helio G96',
    ram: '6 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.43 inches | AMOLED',
    store: 'Mi Store',
    price: '₹15,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'CMF Phone 1',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Unisoc T610',
    ram: '4 GB RAM',
    camera: '13 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.5 inches | IPS LCD',
    store: 'Flipkart',
    price: '₹8,499',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Samsung Galaxy M35 5G',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Exynos 1380',
    ram: '6 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.5 inches | Super AMOLED',
    store: 'Samsung Store',
    price: '₹23,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Moto G85',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'MediaTek Helio G85',
    ram: '4 GB RAM',
    camera: '48 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.5 inches | IPS LCD',
    store: 'Flipkart',
    price: '₹14,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Motorola Edge 50 Fusion',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Qualcomm Snapdragon 8+ Gen 1',
    ram: '12 GB RAM',
    camera: '108 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.8 inches | OLED',
    store: 'Flipkart',
    price: '₹39,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
];
