import 'package:specspot/Model/Mobiles_model.dart';

final List<Phone> mobileunder25k = [
  Phone(
    name: 'Motorola Edge 50 Pro 5G',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Qualcomm Snapdragon 8 Gen 2',
    ram: '12 GB RAM',
    camera: '108 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.8 inches | OLED',
    store: 'Flipkart',
    price: '₹49,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Vivo V30',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'MediaTek Dimensity 9000',
    ram: '8 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '4500 mAh',
    display: '6.5 inches | AMOLED',
    store: 'Amazon',
    price: '₹34,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'OnePlus Nord 4',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Qualcomm Snapdragon 8 Gen 2',
    ram: '12 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '4500 mAh',
    display: '6.74 inches | AMOLED',
    store: 'Amazon',
    price: '₹42,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Realme 13 Pro Plus',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'MediaTek Dimensity 1080',
    ram: '8 GB RAM',
    camera: '108 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.67 inches | Super AMOLED',
    store: 'Flipkart',
    price: '₹27,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Oppo F27 Pro Plus',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'MediaTek Dimensity 920',
    ram: '8 GB RAM',
    camera: '64 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.7 inches | AMOLED',
    store: 'Amazon',
    price: '₹28,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Xiaomi Redmi Note 13 Pro',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Qualcomm Snapdragon 778G',
    ram: '8 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.67 inches | AMOLED',
    store: 'Mi Store',
    price: '₹24,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Samsung Galaxy A35 5G',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Exynos 1380',
    ram: '6 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.5 inches | Super AMOLED',
    store: 'Samsung Store',
    price: '₹23,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Poco F6',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Qualcomm Snapdragon 7+ Gen 2',
    ram: '8 GB RAM',
    camera: '64 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.67 inches | AMOLED',
    store: 'Flipkart',
    price: '₹29,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Poco X6 Pro',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Qualcomm Snapdragon 778G',
    ram: '8 GB RAM',
    camera: '64 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.67 inches | AMOLED',
    store: 'Flipkart',
    price: '₹24,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Motorola Edge 50',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Qualcomm Snapdragon 8 Gen 1',
    ram: '12 GB RAM',
    camera: '108 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.7 inches | OLED',
    store: 'Flipkart',
    price: '₹44,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Samsung Galaxy F55 5G',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Exynos 1380',
    ram: '6 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.5 inches | Super AMOLED',
    store: 'Samsung Store',
    price: '₹22,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Xiaomi Redmi Note 13 Pro Plus 5G',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'MediaTek Dimensity 920',
    ram: '8 GB RAM',
    camera: '108 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.67 inches | AMOLED',
    store: 'Mi Store',
    price: '₹28,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Vivo V30e',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'MediaTek Dimensity 920',
    ram: '8 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '4500 mAh',
    display: '6.44 inches | AMOLED',
    store: 'Amazon',
    price: '₹31,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'OnePlus Nord 3 5G',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'MediaTek Dimensity 9000',
    ram: '8 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '4500 mAh',
    display: '6.74 inches | Fluid AMOLED',
    store: 'Amazon',
    price: '₹29,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Motorola Edge 50 Fusion',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Qualcomm Snapdragon 8+ Gen 1',
    ram: '12 GB RAM',
    camera: '108 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.8 inches | OLED',
    store: 'Flipkart',
    price: '₹39,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Nothing Phone 2a',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Qualcomm Snapdragon 8 Gen 1',
    ram: '8 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '4700 mAh',
    display: '6.7 inches | AMOLED',
    store: 'Flipkart',
    price: '₹39,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Realme 12 Pro',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'MediaTek Helio G96',
    ram: '8 GB RAM',
    camera: '64 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.6 inches | AMOLED',
    store: 'Flipkart',
    price: '₹24,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
];
