import 'package:specspot/Model/Mobiles_model.dart';

final List<Phone> mobileunder10k = [
  Phone(
    name: 'Oppo A38',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'MediaTek Helio G85',
    ram: '4 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.56 inches | IPS LCD',
    store: 'Amazon',
    price: '₹9,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Itel Color Pro 5G',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Unisoc T760',
    ram: '4 GB RAM',
    camera: '48 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.5 inches | IPS LCD',
    store: 'Flipkart',
    price: '₹8,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Vivo Y28e',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'MediaTek Helio P35',
    ram: '4 GB RAM',
    camera: '13 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.51 inches | IPS LCD',
    store: 'Amazon',
    price: '₹9,499',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Poco M6 Pro 5G 128GB',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Qualcomm Snapdragon 695 5G',
    ram: '6 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.67 inches | IPS LCD',
    store: 'Flipkart',
    price: '₹10,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Realme C63',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Unisoc T610',
    ram: '4 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.5 inches | IPS LCD',
    store: 'Flipkart',
    price: '₹8,499',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Infinix Hot 40i',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Unisoc SC9863A',
    ram: '2 GB RAM',
    camera: '8 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.6 inches | IPS LCD',
    store: 'Flipkart',
    price: '₹7,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Vivo Y18',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'MediaTek Helio P35',
    ram: '4 GB RAM',
    camera: '13 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.51 inches | IPS LCD',
    store: 'Amazon',
    price: '₹9,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Realme Narzo N63',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Unisoc T610',
    ram: '4 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.5 inches | IPS LCD',
    store: 'Flipkart',
    price: '₹8,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Realme Narzo N65 5G',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'MediaTek Dimensity 700 5G',
    ram: '6 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.52 inches | IPS LCD',
    store: 'Flipkart',
    price: '₹11,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Samsung Galaxy A14 5G',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Exynos 1330',
    ram: '4 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.6 inches | PLS LCD',
    store: 'Samsung Store',
    price: '₹10,499',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Realme C53',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Unisoc T612',
    ram: '4 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.74 inches | IPS LCD',
    store: 'Flipkart',
    price: '₹9,499',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Moto G24 Power',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Qualcomm Snapdragon 680',
    ram: '4 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.5 inches | IPS LCD',
    store: 'Flipkart',
    price: '₹10,499',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Samsung Galaxy F14 5G',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Exynos 1330',
    ram: '4 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '6000 mAh',
    display: '6.6 inches | PLS LCD',
    store: 'Samsung Store',
    price: '₹10,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Realme 12X',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'MediaTek Helio G88',
    ram: '4 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.72 inches | IPS LCD',
    store: 'Flipkart',
    price: '₹9,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Xiaomi Redmi 13C 5G',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'MediaTek Dimensity 700 5G',
    ram: '4 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.52 inches | IPS LCD',
    store: 'Mi Store',
    price: '₹10,499',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Realme C65 5G',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Unisoc T760 5G',
    ram: '4 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.74 inches | IPS LCD',
    store: 'Flipkart',
    price: '₹10,499',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'iQOO Z9 Lite',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Qualcomm Snapdragon 778G',
    ram: '6 GB RAM',
    camera: '64 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.58 inches | IPS LCD',
    store: 'Amazon',
    price: '₹13,499',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Xiaomi Redmi 12 5G',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'Qualcomm Snapdragon 4 Gen 1',
    ram: '4 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.79 inches | IPS LCD',
    store: 'Mi Store',
    price: '₹10,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
  Phone(
    name: 'Realme Narzo 70X 5G',
    releaseDate: 'Release Date: 2024',
    imageUrls: ['https://via.placeholder.com/150'],
    processor: 'MediaTek Dimensity 6020 5G',
    ram: '4 GB RAM',
    camera: '50 MP Rear Camera',
    battery: '5000 mAh',
    display: '6.58 inches | IPS LCD',
    store: 'Flipkart',
    price: '₹10,999',
    storeIconUrl: 'https://via.placeholder.com/24x24',
  ),
];
