import 'package:specspot/Model/Mobiles_model.dart';

final List<Phone> mobilesunder5k = [
  Phone(
    name: 'Nokia 2660 Flip',
    releaseDate: 'Release Date: 30 Aug, 2022',
    imageUrls: [
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      //"assets/images/mobiles/nokia2660flipimg1.jpg",
      //"assets/images/mobiles/nokia2660flipimg1.jpg",
      //"assets/images/mobiles/nokia2660flipimg1.jpg",
    ],
    processor: 'Unisoc T107',
    ram: '48 MB RAM',
    camera: '0.3 MP Rear Camera',
    battery: '1450 mAh',
    display: '2.8 inches (7.11 cm) | TFT (Main Display)',
    store: 'Amazon',
    price: '₹4,299',
    storeIconUrl: 'assets/icons/amazon_icon.png',
  ),
  Phone(
    name: 'Reliance JioPhone Next',
    releaseDate: 'Release Date: 2021',
    imageUrls: [
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      //"assets/images/mobiles/nokia2660flipimg1.jpg",
      //"assets/images/mobiles/nokia2660flipimg1.jpg",
      //"assets/images/mobiles/nokia2660flipimg1.jpg",
    ],
    processor: 'Qualcomm QM215',
    ram: '2 GB RAM',
    camera: '13 MP Rear Camera',
    battery: '3500 mAh',
    display: '5.45 inches (13.84 cm) | TFT',
    store: 'Flipkart',
    price: '₹4,499',
    storeIconUrl: 'assets/icons/flipkart_icon.png',
  ),
  Phone(
    name: 'Xiaomi Redmi A2 2023 64GB',
    releaseDate: 'Release Date: 2023',
    imageUrls: [
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
    ],
    processor: 'MediaTek Helio G36',
    ram: '4 GB RAM',
    camera: '8 MP + 0.3 MP Dual Rear Camera',
    battery: '5000 mAh',
    display: '6.52 inches (16.56 cm) | IPS LCD',
    store: 'Flipkart',
    price: '₹4,999',
    storeIconUrl: 'assets/icons/flipkart_icon.png',
  ),
  Phone(
    name: 'Nokia 3.1 Plus',
    releaseDate: 'Release Date: 2018',
    imageUrls: [
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
    ],
    processor: 'MediaTek Helio P22',
    ram: '3 GB RAM',
    camera: '13 MP + 5 MP Dual Rear Camera',
    battery: '3500 mAh',
    display: '6.0 inches (15.24 cm) | IPS LCD',
    store: 'Amazon',
    price: '₹4,800',
    storeIconUrl: 'assets/icons/amazon_icon.png',
  ),
  Phone(
    name: 'itel A05s',
    releaseDate: 'Release Date: 2023',
    imageUrls: [
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
    ],
    processor: 'Unisoc SC9832E',
    ram: '2 GB RAM',
    camera: '5 MP Rear Camera',
    battery: '4000 mAh',
    display: '5.0 inches (12.7 cm) | IPS LCD',
    store: 'Amazon',
    price: '₹4,100',
    storeIconUrl: 'assets/icons/amazon_icon.png',
  ),
  Phone(
    name: 'Micromax Canvas Infinity',
    releaseDate: 'Release Date: 2017',
    imageUrls: [
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
    ],
    processor: 'Qualcomm Snapdragon 425',
    ram: '3 GB RAM',
    camera: '13 MP Rear Camera',
    battery: '2980 mAh',
    display: '5.7 inches (14.48 cm) | IPS LCD',
    store: 'Flipkart',
    price: '₹4,200',
    storeIconUrl: 'assets/icons/flipkart_icon.png',
  ),
  Phone(
    name: 'Lava Z70',
    releaseDate: 'Release Date: 2017',
    imageUrls: [
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
    ],
    processor: 'MediaTek MT6737',
    ram: '2 GB RAM',
    camera: '8 MP Rear Camera',
    battery: '2500 mAh',
    display: '5.0 inches (12.7 cm) | IPS LCD',
    store: 'Amazon',
    price: '₹4,500',
    storeIconUrl: 'assets/icons/amazon_icon.png',
  ),
  Phone(
    name: 'Infocus A1',
    releaseDate: 'Release Date: 2018',
    imageUrls: [
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
    ],
    processor: 'Spreadtrum SC9832A',
    ram: '1 GB RAM',
    camera: '5 MP Rear Camera',
    battery: '2200 mAh',
    display: '4.5 inches (11.43 cm) | TFT',
    store: 'Amazon',
    price: '₹4,000',
    storeIconUrl: 'assets/icons/amazon_icon.png',
  ),
  Phone(
    name: 'Micromax Bharat 4',
    releaseDate: 'Release Date: 2017',
    imageUrls: [
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
    ],
    processor: 'MediaTek MT6737',
    ram: '1 GB RAM',
    camera: '5 MP Rear Camera',
    battery: '2000 mAh',
    display: '5.0 inches (12.7 cm) | IPS LCD',
    store: 'Flipkart',
    price: '₹4,300',
    storeIconUrl: 'assets/icons/flipkart_icon.png',
  ),
  Phone(
    name: 'Gionee S10 Lite',
    releaseDate: 'Release Date: 2017',
    imageUrls: [
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
    ],
    processor: 'Qualcomm Snapdragon 427',
    ram: '4 GB RAM',
    camera: '13 MP Rear Camera',
    battery: '3100 mAh',
    display: '5.2 inches (13.21 cm) | IPS LCD',
    store: 'Amazon',
    price: '₹4,700',
    storeIconUrl: 'assets/icons/amazon_icon.png',
  ),
  Phone(
    name: 'Nokia 1',
    releaseDate: 'Release Date: 2018',
    imageUrls: [
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
    ],
    processor: 'MediaTek MT6737M',
    ram: '1 GB RAM',
    camera: '5 MP Rear Camera',
    battery: '2150 mAh',
    display: '4.5 inches (11.43 cm) | IPS LCD',
    store: 'Flipkart',
    price: '₹4,000',
    storeIconUrl: 'assets/icons/flipkart_icon.png',
  ),
  Phone(
    name: 'Coolpad Cool 5',
    releaseDate: 'Release Date: 2019',
    imageUrls: [
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
    ],
    processor: 'MediaTek Helio P22',
    ram: '4 GB RAM',
    camera: '13 MP + 2 MP Dual Rear Camera',
    battery: '4000 mAh',
    display: '6.22 inches (15.8 cm) | IPS LCD',
    store: 'Amazon',
    price: '₹4,999',
    storeIconUrl: 'assets/icons/amazon_icon.png',
  ),
  Phone(
    name: 'itel A48',
    releaseDate: 'Release Date: 2020',
    imageUrls: [
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
    ],
    processor: 'Unisoc SC9832E',
    ram: '2 GB RAM',
    camera: '5 MP Rear Camera',
    battery: '3000 mAh',
    display: '6.1 inches (15.49 cm) | IPS LCD',
    store: 'Amazon',
    price: '₹4,299',
    storeIconUrl: 'assets/icons/amazon_icon.png',
  ),
  Phone(
    name: 'iKall Z6 Pro',
    releaseDate: 'Release Date: 2022',
    imageUrls: [
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
    ],
    processor: 'Unisoc SC9863A',
    ram: '4 GB RAM',
    camera: '8 MP Rear Camera',
    battery: '4000 mAh',
    display: '6.26 inches (15.9 cm) | IPS LCD',
    store: 'Flipkart',
    price: '₹4,799',
    storeIconUrl: 'assets/icons/flipkart_icon.png',
  ),
  Phone(
    name: 'iKall Z3 New',
    releaseDate: 'Release Date: 2022',
    imageUrls: [
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
    ],
    processor: 'Unisoc SC9832E',
    ram: '3 GB RAM',
    camera: '5 MP Rear Camera',
    battery: '3000 mAh',
    display: '5.5 inches (13.97 cm) | IPS LCD',
    store: 'Flipkart',
    price: '₹4,199',
    storeIconUrl: 'assets/icons/flipkart_icon.png',
  ),
  Phone(
    name: 'iKall Z11 Pro',
    releaseDate: 'Release Date: 2023',
    imageUrls: [
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
    ],
    processor: 'Unisoc SC9863A',
    ram: '4 GB RAM',
    camera: '8 MP + 0.3 MP Dual Rear Camera',
    battery: '4000 mAh',
    display: '6.52 inches (16.56 cm) | IPS LCD',
    store: 'Flipkart',
    price: '₹4,999',
    storeIconUrl: 'assets/icons/flipkart_icon.png',
  ),
  Phone(
    name: 'LYF Earth 2',
    releaseDate: 'Release Date: 2016',
    imageUrls: [
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
      "assets/images/mobiles/nokia2660flipimg1.jpg",
    ],
    processor: 'Qualcomm Snapdragon 615',
    ram: '3 GB RAM',
    camera: '13 MP Rear Camera',
    battery: '2500 mAh',
    display: '5.0 inches (12.7 cm) | IPS LCD',
    store: 'Amazon',
    price: '₹4,799',
    storeIconUrl: 'assets/icons/amazon_icon.png',
  ),
];
